version: '3'
services:
  db:
    image: postgres:16-alpine
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    env_file: .env

  web:
    image: aleksey2299/security_backend:latest
    volumes:
      - static:/backend_static
      - media:/code/media
    depends_on:
      - db
    env_file: .env

  # update_prices:
  #   build: ./backend
  #   command: python manage.py update_prices
  #   volumes:
  #     - ./backend:/code/
  #   depends_on:
  #     - db

  # bot:
  #   build: ./backend/
  #   command: python manage.py bot
  #   volumes:
  #     - ./backend:/code
  #   depends_on:
  #     - db

  next:
    image: natashasolntseva/security_frontend:latest
    env_file: .env
    depends_on:
      - web

  nginx:
    image: aleksey2299/security_nginx:latest
    env_file: .env
    ports:
      - 8000:80
      - 443:443
    volumes:
      - static:/static/
      - media:/media/
      - certs:/etc/letsencrypt
    depends_on:
      - web

volumes:
  pgdbdata:
  static:
  media:
  certs:
