version: '3'
services:
  db:
    image: postgres:16-alpine
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    env_file: .env

  web:
    build: ./backend/
    volumes:
      - ./backend:/code
    ports:
      - 8001:8000
    depends_on:
      - db
    env_file: .env

  # update_prices:
  #   build: ./backend
  #   command: python manage.py update_prices
  #   volumes:
  #     - ./backend:/code/
  #   depends_on:
  #     - db

  # bot:
  #   build: ./backend/
  #   command: python manage.py bot
  #   volumes:
  #     - ./backend:/code
  #   depends_on:
  #     - db

volumes:
  pgdbdata:
