# Generated by Django 4.2.11 on 2024-05-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0010_remove_camera_description_remove_camera_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "setup_inner_camera_easy",
                    models.IntegerField(
                        verbose_name="Простая установка внутренней камеры"
                    ),
                ),
                (
                    "setup_inner_camera",
                    models.IntegerField(verbose_name="Установка внутренней камеры"),
                ),
                (
                    "setup_inner_camera_hard",
                    models.IntegerField(
                        verbose_name="Сложная установка внутренней камеры"
                    ),
                ),
                (
                    "cabel_price_for_inner_cameras_per_meter",
                    models.IntegerField(
                        verbose_name="Цена за 1 метра кабеля для внутренних камер"
                    ),
                ),
                (
                    "setup_outer_camera_easy",
                    models.IntegerField(
                        verbose_name="Простая установка внешней камеры"
                    ),
                ),
                (
                    "setup_outer_camera",
                    models.IntegerField(verbose_name="Установка внешней камеры"),
                ),
                (
                    "setup_outer_camera_hard",
                    models.IntegerField(
                        verbose_name="Сложная установка внешней камеры"
                    ),
                ),
                (
                    "cabel_price_for_outer_cameras_per_meter",
                    models.IntegerField(
                        verbose_name="Цена за 1 метра кабеля для внешних камер"
                    ),
                ),
                (
                    "setup_ahd_registery",
                    models.IntegerField(
                        verbose_name="Установка регистратора AHD системы"
                    ),
                ),
                (
                    "setup_ip_registery",
                    models.IntegerField(
                        verbose_name="Установка регистратора IP системы"
                    ),
                ),
                (
                    "price_multiplier_for_registery_setup",
                    models.IntegerField(
                        verbose_name="Множитель цены установки регистратора если больше 16 камер"
                    ),
                ),
                (
                    "registery_4",
                    models.IntegerField(
                        verbose_name="Цена регистратора при 4 и меньше камерах"
                    ),
                ),
                (
                    "registery_8",
                    models.IntegerField(
                        verbose_name="Цена регистратора при 4 и меньше камерах"
                    ),
                ),
                (
                    "registery_16",
                    models.IntegerField(
                        verbose_name="Цена регистратора при 4 и меньше камерах"
                    ),
                ),
                (
                    "registery_20",
                    models.IntegerField(
                        verbose_name="Цена регистратора при 4 и меньше камерах"
                    ),
                ),
                (
                    "registery_24",
                    models.IntegerField(
                        verbose_name="Цена регистратора при 4 и меньше камерах"
                    ),
                ),
                (
                    "registery_32",
                    models.IntegerField(
                        verbose_name="Цена регистратора при 4 и меньше камерах"
                    ),
                ),
                (
                    "power_unit",
                    models.IntegerField(
                        verbose_name="Цена блока питания с работой (цена увеличивается каждые 5 камер)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Прайс лист",
            },
        ),
    ]
