# Generated by Django 4.2.11 on 2024-05-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0011_pricelist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Camera",
        ),
        migrations.DeleteModel(
            name="CameraPrice",
        ),
        migrations.AlterModelOptions(
            name="pricelist",
            options={
                "verbose_name": "Прайс лист",
                "verbose_name_plural": "Прайс листы",
            },
        ),
        migrations.AddField(
            model_name="pricelist",
            name="is_current",
            field=models.BooleanField(
                default=False, verbose_name="Актуальный прайс лист"
            ),
        ),
    ]
