# Generated by Django 4.2.11 on 2024-05-16 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0012_delete_camera_delete_cameraprice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calculator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Калькулятор",
                "verbose_name_plural": "Калькуляторы",
            },
        ),
        migrations.CreateModel(
            name="Formula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expression", models.CharField(verbose_name="Формула")),
            ],
            options={
                "verbose_name": "Формула",
                "verbose_name_plural": "Формулы",
            },
        ),
        migrations.CreateModel(
            name="CalculatorBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40, verbose_name="Название")),
                (
                    "calculator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="calculator.calculator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок калькулятора",
                "verbose_name_plural": "Блоки калькулятора",
            },
        ),
        migrations.AddField(
            model_name="calculator",
            name="formula",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="calculator.formula",
            ),
        ),
        migrations.AddField(
            model_name="calculator",
            name="price_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="calculator.pricelist",
            ),
        ),
        migrations.CreateModel(
            name="BlockOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40, verbose_name="Название")),
                ("desription", models.CharField(verbose_name="Описание")),
                (
                    "option_type",
                    models.CharField(
                        choices=[
                            ("number", "Число"),
                            ("radio", "Выбор"),
                            ("checkbox", "Подтверждение"),
                        ],
                        verbose_name="Тип опции",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Имя переменной для формулы",
                        max_length=20,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "choices",
                    models.CharField(
                        blank=True,
                        help_text="перечислите варианты через ';'",
                        null=True,
                        verbose_name="Выбор",
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculator.calculatorblock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опция для блока",
                "verbose_name_plural": "Опции блока",
            },
        ),
    ]
