# Generated by Django 4.2.11 on 2024-05-16 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0013_calculator_formula_calculatorblock_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blockoption",
            old_name="desription",
            new_name="description",
        ),
        migrations.AddField(
            model_name="calculatorblock",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="media/calculator",
                verbose_name="Значок",
            ),
        ),
        migrations.AlterField(
            model_name="blockoption",
            name="block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="calculator.calculatorblock",
            ),
        ),
        migrations.AlterField(
            model_name="blockoption",
            name="choices",
            field=models.CharField(
                blank=True,
                help_text="Перечислите варианты через ';'",
                null=True,
                verbose_name="Выбор",
            ),
        ),
        migrations.AlterField(
            model_name="blockoption",
            name="name",
            field=models.CharField(
                help_text="Имя переменной для формулы",
                max_length=40,
                verbose_name="Имя",
            ),
        ),
        migrations.AlterField(
            model_name="calculatorblock",
            name="calculator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blocks",
                to="calculator.calculator",
            ),
        ),
    ]
