# Generated by Django 4.2.11 on 2024-05-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0014_rename_desription_blockoption_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockoption",
            name="product",
            field=models.CharField(
                blank=True,
                help_text='Название категории + фильтры (если нужны) в скобках. Например: camera(type="HD", price__lt=1000)',
                null=True,
                verbose_name="Продукт для фильтрации",
            ),
        ),
        migrations.AlterField(
            model_name="blockoption",
            name="name",
            field=models.CharField(
                help_text="Имя переменной для формулы или имя поля модели",
                max_length=40,
                verbose_name="Имя",
            ),
        ),
        migrations.AlterField(
            model_name="formula",
            name="expression",
            field=models.TextField(verbose_name="Формула"),
        ),
    ]
