# Generated by Django 4.2.11 on 2024-05-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0016_remove_calculator_formula_blockoption_filters_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockoption",
            name="filters",
            field=models.TextField(
                blank=True,
                help_text="Фильтры перечисленые через запятую.\nДоступные операторы:\n1. Равенство: ==.\n2. Неравенство: !=.\n3. Больше: >.\n4. Меньше: <.\n5. Больше или равно: >=.\n6. Меньше или равно: <=.\nПример: type == HD, price <= 1000",
                null=True,
                verbose_name="Фильтры для товара",
            ),
        ),
    ]
