# Generated by Django 4.2.13 on 2024-06-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0017_alter_blockoption_filters"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricelist",
            name="fields",
            field=models.JSONField(default=1, verbose_name="Прайс лист"),
            preserve_default=False,
        ),
    ]
