# Generated by Django 4.2.13 on 2024-06-01 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0019_remove_pricelist_is_current"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricelist",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
    ]
