# Generated by Django 4.2.13 on 2024-06-01 15:18

import calculator.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0020_pricelist_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricelist",
            name="cabel_price_for_inner_cameras_per_meter",
        ),
        migrations.RemoveField(
            model_name="pricelist",
            name="cabel_price_for_outer_cameras_per_meter",
        ),
        migrations.RemoveField(
            model_name="pricelist",
            name="fields",
        ),
        migrations.RemoveField(
            model_name="pricelist",
            name="power_unit",
        ),
        migrations.RemoveField(
            model_name="pricelist",
            name="price_multiplier_for_registery_setup",
        ),
        migrations.RemoveField(
            model_name="pricelist",
            name="registery_16",
        ),
        migrations.RemoveField(
            model_name="pricelist",
            name="registery_20",
        ),
        migrations.RemoveField(
            model_name="pricelist",
            name="registery_24",
        ),
        migrations.RemoveField(
            model_name="pricelist",
            name="registery_32",
        ),
        migrations.RemoveField(
            model_name="pricelist",
            name="registery_4",
        ),
        migrations.RemoveField(
            model_name="pricelist",
            name="registery_8",
        ),
        migrations.RemoveField(
            model_name="pricelist",
            name="setup_ahd_registery",
        ),
        migrations.RemoveField(
            model_name="pricelist",
            name="setup_inner_camera",
        ),
        migrations.RemoveField(
            model_name="pricelist",
            name="setup_inner_camera_easy",
        ),
        migrations.RemoveField(
            model_name="pricelist",
            name="setup_inner_camera_hard",
        ),
        migrations.RemoveField(
            model_name="pricelist",
            name="setup_ip_registery",
        ),
        migrations.RemoveField(
            model_name="pricelist",
            name="setup_outer_camera",
        ),
        migrations.RemoveField(
            model_name="pricelist",
            name="setup_outer_camera_easy",
        ),
        migrations.RemoveField(
            model_name="pricelist",
            name="setup_outer_camera_hard",
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="Название услуги/товара")),
                (
                    "variable_name",
                    models.CharField(
                        blank=True,
                        help_text="Имя переменной в калькуляторе",
                        max_length=200,
                        null=True,
                        validators=[calculator.validators.validate_latin_underscore],
                        verbose_name="Переменная",
                    ),
                ),
                (
                    "is_show",
                    models.BooleanField(
                        help_text="Отображать ли эту цену в прайс листе",
                        verbose_name="Показывать клиенту",
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prices",
                        to="calculator.pricelist",
                    ),
                ),
            ],
        ),
    ]
