# Generated by Django 4.2.13 on 2024-06-01 15:45

import calculator.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculator",
            "0021_remove_pricelist_cabel_price_for_inner_cameras_per_meter_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="calculator",
            name="is_active",
            field=models.BooleanField(
                default=False, verbose_name="Текущий калькулятор"
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="price",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="price",
            name="variable_name",
            field=models.CharField(
                blank=True,
                help_text="Имя переменной в калькуляторе (латинские символы и нижнее подчеркивание)",
                max_length=200,
                null=True,
                validators=[calculator.validators.validate_latin_underscore],
                verbose_name="Переменная",
            ),
        ),
    ]
