# Generated by Django 4.2.13 on 2024-06-01 15:47

import calculator.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0022_calculator_is_active_price_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="variable_name",
            field=models.CharField(
                blank=True,
                help_text="Имя переменной в калькуляторе (латинские символы, цифры и нижнее подчеркивание)",
                max_length=200,
                null=True,
                validators=[calculator.validators.validate_latin_underscore],
                verbose_name="Переменная",
            ),
        ),
    ]
