# Generated by Django 4.2.13 on 2024-07-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0023_alter_price_variable_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculatorblock",
            name="quantity_selection",
            field=models.BooleanField(
                default=True,
                help_text="Предоставить пользователю выбор кол-ва товара (иначе это будет выбор между 'да' и 'нет')",
                verbose_name="Выбор кол-ва",
            ),
        ),
    ]
