# Generated by Django 4.2.13 on 2024-07-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0024_calculatorblock_quantity_selection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockoption",
            name="option_type",
            field=models.CharField(
                choices=[
                    ("number", "Число"),
                    ("radio", "Выбор"),
                    ("checkbox", "Подтверждение"),
                    ("counter", "Счетчик"),
                ],
                verbose_name="Тип опции",
            ),
        ),
    ]
