# Generated by Django 4.2.13 on 2024-07-10 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0026_alter_blockoption_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockoption",
            name="depends_on",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="calculator.blockoption",
                verbose_name="Зависит от опции",
            ),
        ),
        migrations.AddField(
            model_name="blockoption",
            name="depends_on_value",
            field=models.CharField(
                blank=True, verbose_name="Зависит от значения опции"
            ),
        ),
    ]
