# Generated by Django 4.2.13 on 2024-07-11 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0027_blockoption_depends_on_blockoption_depends_on_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockoption",
            name="depends_on",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dependent",
                to="calculator.blockoption",
                verbose_name="Зависит от опции",
            ),
        ),
    ]
