# Generated by Django 4.2.13 on 2024-07-12 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0028_alter_blockoption_depends_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="price",
            name="price_list",
        ),
        migrations.AddField(
            model_name="formula",
            name="name",
            field=models.CharField(
                default="unknown", max_length=100, verbose_name="Название"
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="PriceListCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "price_list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="categories",
                        to="calculator.pricelist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория прайс листа",
                "verbose_name_plural": "Категории прайс листов",
            },
        ),
        migrations.AddField(
            model_name="price",
            name="price_list_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prices",
                to="calculator.pricelistcategory",
            ),
        ),
    ]
