# Generated by Django 4.2.13 on 2024-07-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0029_remove_price_price_list_formula_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="price",
            options={"verbose_name": "Цена", "verbose_name_plural": "Цены"},
        ),
        migrations.AlterField(
            model_name="pricelist",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата последнего обновления"
            ),
        ),
    ]
