# Generated by Django 4.2.13 on 2024-07-12 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0030_alter_price_options_alter_pricelist_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="calculator",
            old_name="is_active",
            new_name="active",
        ),
    ]
