# Generated by Django 4.2.13 on 2024-07-26 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0026_alter_camera_accommodation_alter_camera_focus_and_more"),
        ("calculator", "0031_rename_is_active_calculator_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockoption",
            name="price",
            field=models.ForeignKey(
                blank=True,
                help_text="Связать с ценой из прайс листа",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="calculator.price",
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Связать с ценой товара",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prices_in_price_lists",
                to="product.product",
            ),
        ),
    ]
