# Generated by Django 4.2.13 on 2024-07-26 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0027_otherproduct_remove_pacsproduct_product_ptr_and_more"),
        ("calculator", "0032_blockoption_price_price_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blockoption",
            name="product",
        ),
        migrations.AddField(
            model_name="blockoption",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.productcategory",
                verbose_name="Категория продукта для фильтрации",
            ),
        ),
    ]
