# Generated by Django 4.2.13 on 2024-07-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0033_alter_blockoption_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockoption",
            name="amount_depend",
            field=models.CharField(
                blank=True,
                help_text="Название переменной другой опции из этого блока",
                null=True,
                verbose_name="Зависит от переменной",
            ),
        ),
        migrations.AddField(
            model_name="blockoption",
            name="block_amount_undependent",
            field=models.BooleanField(
                default=False, verbose_name="Не зависит от кол-ва в самом блоке"
            ),
        ),
    ]
