# Generated by Django 4.2.13 on 2024-07-30 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0031_alter_hdd_capacity"),
        ("calculator", "0034_blockoption_amount_depend_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockoption",
            name="initial_value",
            field=models.IntegerField(
                blank=True,
                help_text="Можно оставить пустым для 1 (при условии, что выбрана изменяемость)",
                null=True,
                verbose_name="Начальное числовое значение",
            ),
        ),
        migrations.AddField(
            model_name="blockoption",
            name="variability_with_block_amount",
            field=models.BooleanField(
                default=False,
                help_text="Нельзя использовать вместе с категорией продукции",
                verbose_name="Изменяется вместе с кол-вом в блоке",
            ),
        ),
        migrations.AlterField(
            model_name="blockoption",
            name="amount_depend",
            field=models.CharField(
                blank=True,
                help_text="Название переменной другой опции из этого блока",
                null=True,
                verbose_name="Кол-во товара зависит от переменной",
            ),
        ),
        migrations.AlterField(
            model_name="blockoption",
            name="block_amount_undependent",
            field=models.BooleanField(
                default=False,
                help_text="Не будет учитываться если нет связи с категорией продукции",
                verbose_name="Кол-во товара не зависит от кол-ва в самом блоке",
            ),
        ),
        migrations.AlterField(
            model_name="blockoption",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.productcategory",
                verbose_name="Категория товара для фильтрации",
            ),
        ),
    ]
