# Generated by Django 4.2.13 on 2024-09-29 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("calculator", "0038_alter_productoption_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productoption",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_options",
                to="contenttypes.contenttype",
                verbose_name="Категория товара для фильтрации",
            ),
        ),
    ]
