# Generated by Django 4.2.13 on 2024-11-09 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("calculator", "0039_alter_productoption_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="valueoption",
            name="variability_with_block_amount",
            field=models.BooleanField(
                default=False, verbose_name="Изменяется вместе с кол-вом в блоке"
            ),
        ),
        migrations.CreateModel(
            name="Calculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "amount",
                    models.TextField(
                        help_text="Значение или формула для вычисления значения",
                        verbose_name="Кол-во",
                    ),
                ),
                ("filters", models.TextField(verbose_name="Фильтры для товара")),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculations",
                        to="calculator.calculatorblock",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="Категория товара",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
