# Generated by Django 4.2.13 on 2024-11-11 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product",
            "0044_alter_productproperty_options_alter_newproduct_model_and_more",
        ),
        ("calculator", "0041_alter_calculation_options_price_new_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calculation",
            name="product",
        ),
        migrations.RemoveField(
            model_name="price",
            name="product",
        ),
        migrations.AlterField(
            model_name="productoption",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_options",
                to="product.producttype",
                verbose_name="Категория товара для фильтрации",
            ),
        ),
    ]
