# Generated by Django 4.2.13 on 2025-01-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0044_alter_calculation_filters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productoption",
            name="name",
            field=models.CharField(
                help_text="Имя поля модели, или 'self' если тут происходит выбор кол-ва товара",
                max_length=40,
                verbose_name="Имя",
            ),
        ),
    ]
