# Generated by Django 4.2.13 on 2025-01-20 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0045_alter_productoption_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricelistcategory",
            name="price_list",
        ),
        migrations.RemoveField(
            model_name="calculator",
            name="price_list",
        ),
        migrations.RemoveField(
            model_name="valueoption",
            name="price",
        ),
        migrations.DeleteModel(
            name="Price",
        ),
        migrations.DeleteModel(
            name="PriceList",
        ),
        migrations.DeleteModel(
            name="PriceListCategory",
        ),
    ]
