# Generated by Django 4.2.13 on 2025-01-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0046_remove_pricelistcategory_price_list_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockoption",
            name="depends_on_value",
            field=models.CharField(
                blank=True, null=True, verbose_name="Зависит от значения опции"
            ),
        ),
        migrations.AlterField(
            model_name="valueoption",
            name="name",
            field=models.CharField(
                help_text="Имя переменной для формул", max_length=40, verbose_name="Имя"
            ),
        ),
    ]
