# Generated by Django 4.2.13 on 2025-02-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0047_alter_blockoption_depends_on_value_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="valueoption",
            name="initial_value",
        ),
        migrations.RemoveField(
            model_name="valueoption",
            name="variability_with_block_amount",
        ),
        migrations.AddField(
            model_name="blockoption",
            name="initial_value",
            field=models.IntegerField(
                blank=True,
                help_text="Можно оставить пустым для 1 (при условии, что выбрана изменяемость)",
                null=True,
                verbose_name="Начальное числовое значение",
            ),
        ),
        migrations.AddField(
            model_name="blockoption",
            name="variability_with_block_amount",
            field=models.BooleanField(
                default=False,
                verbose_name="Изменяется вместе с кол-вом в блоке (<strong>только если опция числовая</strong>)",
            ),
        ),
        migrations.AlterField(
            model_name="productoption",
            name="name",
            field=models.CharField(
                help_text="Имя поля модели, или имя начинающееся на 'self' если тут происходит выбор кол-ва товара (поле будет называться <strong><данное имя>_&lt;id категории товара></strong>)",
                max_length=40,
                verbose_name="Имя",
            ),
        ),
    ]
