# Generated by Django 4.2.13 on 2025-02-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0048_remove_valueoption_initial_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockoption",
            name="variability_with_block_amount",
            field=models.BooleanField(
                default=False,
                help_text="<strong>Только если опция числовая</strong>",
                verbose_name="Изменяется вместе с кол-вом в блоке)",
            ),
        ),
    ]
