# Generated by Django 4.2.13 on 2025-02-15 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0052_alter_newproduct_options_and_more"),
        ("calculator", "0049_alter_blockoption_variability_with_block_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculatorblock",
            name="main_product",
            field=models.ForeignKey(
                blank=True,
                help_text="Если подходящего под условия товара не окажется, то значение всего блока будет 0.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.producttype",
                verbose_name="Категория главного товара",
            ),
        ),
        migrations.AlterField(
            model_name="blockoption",
            name="initial_value",
            field=models.CharField(
                blank=True,
                help_text="Если выбрана изменяемость, то это поле может быть только числом (по умолчанию равно 1). Иначе тут должно быть соответствующее типу опции значение (true, false - для подтверждения, один из вариантов - для выбора)",
                null=True,
                verbose_name="Начальное значение",
            ),
        ),
    ]
