[tool.black]
target-version = ['py312']

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "main.settings"
norecursedirs = "env/* venv/*"
addopts = [
    "-vv",
    "-p",
    "no:cacheprovider",
]
testpaths = "tests/"
python_files = "test_*.py"
