# Generated by Django 5.0.1 on 2024-04-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Image_Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/our_works', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name': 'Фотографии',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Производителя',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/service', verbose_name='Фотография')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Наши услуги',
                'verbose_name_plural': 'Наши услуги',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('answer', models.TextField(max_length=500, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос/Ответ',
                'verbose_name_plural': 'Вопрос/Ответ',
            },
        ),
        migrations.CreateModel(
            name='OurWorks',
            fields=[
                ('title', models.CharField(max_length=400, verbose_name='Предложение')),
                ('main_image', models.ImageField(upload_to='media/ourworks', verbose_name='Фотография')),
                ('product', models.TextField(max_length=500, verbose_name='Используемое оборудование')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('price', models.IntegerField(primary_key=True, serialize=False, verbose_name='Цена')),
                ('add_date', models.DateTimeField(verbose_name='Дата добавление на сайт')),
                ('deadline', models.CharField(max_length=50, verbose_name='Сроки')),
                ('budget', models.CharField(max_length=50, verbose_name='Бюджет')),
                ('equipped', models.CharField(max_length=50, verbose_name='Оборудовано')),
                ('image', models.ManyToManyField(to='product.image_works', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name': 'Примеры работ',
                'verbose_name_plural': 'Примеры работ',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=50, verbose_name='Артикул')),
                ('model', models.CharField(max_length=300, verbose_name='Модель')),
                ('image', models.ImageField(upload_to='media/camera', verbose_name='Изображение')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('form_factor', models.CharField(choices=[('Domed', 'Купольная'), ('Cylindrical', 'Цилиндрическая')], max_length=20, verbose_name='Форм Фактор')),
                ('accommodation', models.CharField(choices=[('Street', 'Уличное'), ('Internal', 'Внутренняя')], max_length=30, verbose_name='Размещение')),
                ('resolution', models.CharField(max_length=30, verbose_name='Разрешение')),
                ('dark', models.CharField(max_length=30, verbose_name='Съемка в темноте')),
                ('temperature', models.CharField(max_length=30, verbose_name='Температура')),
                ('nutrition', models.CharField(max_length=30, verbose_name='Питание')),
                ('microphone', models.CharField(choices=[('No', 'Нет'), ('Microphone', 'Микрофон'), ('Microphone_speaker', 'Микрофон/Динамик')], max_length=30, verbose_name='Микрофон')),
                ('micro_sd', models.CharField(max_length=30, verbose_name='MicroSD')),
                ('viewing_angle', models.CharField(max_length=30, verbose_name='Угол Обзора')),
                ('focus', models.CharField(max_length=30, verbose_name='Фокус')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('category', models.ManyToManyField(to='product.category', verbose_name='Категория')),
                ('manufacturer', models.ManyToManyField(to='product.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ReadySolutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/ready', verbose_name='Фотография')),
                ('title', models.CharField(max_length=100, verbose_name='Предложение')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
                ('short_description', models.CharField(max_length=50, verbose_name='Краткое описание')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('category', models.ManyToManyField(to='product.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Готовые решение',
                'verbose_name_plural': 'Готовые решение',
            },
        ),
    ]
