# Generated by Django 5.0.1 on 2024-01-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/our_works', verbose_name='Фотографии')),
            ],
        ),
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/service', verbose_name='Фотография')),
                ('descriptoin', models.TextField(max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Наши услуги',
                'verbose_name_plural': 'Наши услуги',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('model', models.CharField(max_length=30, verbose_name='Модель')),
                ('image', models.ImageField(upload_to='media/camera', verbose_name='Изображение')),
                ('descriptoin', models.TextField(max_length=500, verbose_name='Описание')),
                ('manufacturer', models.CharField(max_length=30, verbose_name='Производитель')),
                ('accommodation', models.CharField(max_length=30, verbose_name='Размещение')),
                ('resolution', models.CharField(max_length=30, verbose_name='Разрешение')),
                ('dark', models.CharField(max_length=30, verbose_name='Съемка в темноте')),
                ('temperature', models.CharField(max_length=30, verbose_name='Температура')),
                ('nutrition', models.CharField(max_length=30, verbose_name='Питание')),
                ('microphone', models.CharField(max_length=30, verbose_name='Микрофон')),
                ('micro_sd', models.CharField(max_length=30, verbose_name='MicroSD')),
                ('viewing_angle', models.CharField(max_length=30, verbose_name='Угол Обзора')),
                ('focus', models.CharField(max_length=30, verbose_name='Фокус')),
                ('category', models.CharField(max_length=30, verbose_name='Категория')),
                ('price', models.IntegerField(primary_key=True, serialize=False, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='OurWorks',
            fields=[
                ('descriptoin', models.TextField(max_length=500, verbose_name='Описание')),
                ('price', models.IntegerField(primary_key=True, serialize=False, verbose_name='Цена')),
                ('date_works', models.DateTimeField(verbose_name='Дата выполнение проекта')),
                ('add_date', models.DateTimeField(verbose_name='Дата добавление на сайт')),
                ('image', models.ManyToManyField(to='product.image_works', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Примеры работ',
                'verbose_name_plural': 'Примеры работ',
            },
        ),
        migrations.CreateModel(
            name='PopularSolutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Предложение')),
                ('product', models.ManyToManyField(to='product.product', verbose_name='Популярный продукт')),
            ],
            options={
                'verbose_name': 'Готовые решение',
                'verbose_name_plural': 'Готовые решение',
            },
        ),
    ]
