# Generated by Django 5.0.1 on 2024-03-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Image_Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/our_works', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name': 'Фотографии',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/service', verbose_name='Фотография')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Наши услуги',
                'verbose_name_plural': 'Наши услуги',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=300)),
                ('model', models.CharField(max_length=30, verbose_name='Модель')),
                ('image', models.ImageField(upload_to='media/camera', verbose_name='Изображение')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('manufacturer', models.CharField(max_length=30, verbose_name='Производитель')),
                ('accommodation', models.CharField(max_length=30, verbose_name='Размещение')),
                ('resolution', models.CharField(max_length=30, verbose_name='Разрешение')),
                ('dark', models.CharField(max_length=30, verbose_name='Съемка в темноте')),
                ('temperature', models.CharField(max_length=30, verbose_name='Температура')),
                ('nutrition', models.CharField(max_length=30, verbose_name='Питание')),
                ('microphone', models.CharField(max_length=30, verbose_name='Микрофон')),
                ('micro_sd', models.CharField(max_length=30, verbose_name='MicroSD')),
                ('viewing_angle', models.CharField(max_length=30, verbose_name='Угол Обзора')),
                ('focus', models.CharField(max_length=30, verbose_name='Фокус')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('category', models.ManyToManyField(to='product.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='OurWorks',
            fields=[
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('price', models.IntegerField(primary_key=True, serialize=False, verbose_name='Цена')),
                ('date_works', models.DateTimeField(verbose_name='Дата начало проекта')),
                ('date_finish', models.DateTimeField(verbose_name='Дата окончание проекта')),
                ('add_date', models.DateTimeField(verbose_name='Дата добавление на сайт')),
                ('image', models.ManyToManyField(to='product.image_works', verbose_name='Фотография')),
                ('product', models.ManyToManyField(to='product.product', verbose_name='Используемое оборудование')),
            ],
            options={
                'verbose_name': 'Примеры работ',
                'verbose_name_plural': 'Примеры работ',
            },
        ),
        migrations.CreateModel(
            name='ReadySolutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Предложение')),
                ('description', models.TextField(max_length=300, verbose_name='Полное описание')),
                ('short_description', models.CharField(max_length=50, verbose_name='Краткое описание')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Итог')),
                ('product', models.ManyToManyField(to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Готовые решение',
                'verbose_name_plural': 'Готовые решение',
            },
        ),
    ]
