# Generated by Django 5.0.1 on 2024-03-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_product_id_product_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=50, verbose_name='Артикул'),
        ),
    ]
