# Generated by Django 5.0.1 on 2024-03-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='form_factor',
            field=models.CharField(default='', max_length=20, verbose_name='Форм Фактор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
