# Generated by Django 4.2.11 on 2024-04-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_ourservice_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="category",
            field=models.CharField(
                choices=[
                    ("Общие Вопросы", "Общие Вопросы"),
                    ("Вопросы по видеонаблюдению", "Вопросы по видеонаблюдению"),
                    ("Вопросы по домофонии", "Вопросы по домофонии"),
                    (
                        "Вопросы по биометрии и системам контроля учёта доступа",
                        "Вопросы по биометрии и системам контроля учёта доступа",
                    ),
                    (
                        "Вопросы по шлагбаумам и турникетам (в СКУД)",
                        "Вопросы по шлагбаумам и турникетам (в СКУД)",
                    ),
                    (
                        "Вопросы по охранно-пожарной сигнализации",
                        "Вопросы по охранно-пожарной сигнализации",
                    ),
                ],
                verbose_name="Категории",
            ),
        ),
    ]
