# Generated by Django 5.0.1 on 2024-03-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_form_factor_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='form_factor',
            field=models.CharField(choices=[('Domed', 'Купольная'), ('Cylindrical', 'Цилиндрическая')], max_length=20, verbose_name='Форм Фактор'),
        ),
    ]
