# Generated by Django 5.0.1 on 2024-01-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.ManyToManyField(blank=True, to='product.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='resolution',
            field=models.CharField(blank=True, max_length=20, verbose_name='Разрешение'),
        ),
    ]
