# Generated by Django 5.0.1 on 2024-03-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_form_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='accommodation',
            field=models.CharField(choices=[('Street', 'Уличное'), ('Internal', 'Внутренняя')], max_length=30, verbose_name='Размещение'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
        migrations.AlterField(
            model_name='product',
            name='microphone',
            field=models.CharField(choices=[('No', 'Нет'), ('Microphone', 'Микрофон'), ('Microphone_speaker', 'Микрофон/Динамик')], max_length=30, verbose_name='Микрофон'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ManyToManyField(to='product.manufacturer', verbose_name='Производитель'),
        ),
    ]
