# Generated by Django 5.0.1 on 2024-01-31 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image_works',
            options={'verbose_name': 'Фотографии', 'verbose_name_plural': 'Фотографии'},
        ),
    ]
