# Generated by Django 5.0.1 on 2024-01-08 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_popularsolutions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popularsolutions',
            old_name='popular_solutions',
            new_name='product',
        ),
    ]
