# Generated by Django 5.0.1 on 2024-03-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_manufacturer_alter_product_accommodation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Производителя', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=300, verbose_name='Модель'),
        ),
    ]
