# Generated by Django 4.2.11 on 2024-05-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_hdd_article_product_type_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='image',
            field=models.ImageField(default='', upload_to='media/register', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
