# Generated by Django 5.0.1 on 2024-02-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_image_works_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptoin',
            new_name='description',
        ),
    ]
