# Generated by Django 5.0.1 on 2024-01-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_popular_solutions_popularsolutions_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularsolutions',
            name='product',
        ),
        migrations.AddField(
            model_name='popularsolutions',
            name='product',
            field=models.ManyToManyField(to='product.product'),
        ),
    ]
