# Generated by Django 5.0.1 on 2024-01-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_popularsolutions_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popularsolutions',
            options={'verbose_name': 'Популярные продукты', 'verbose_name_plural': 'Популярные продукты'},
        ),
        migrations.AddField(
            model_name='popularsolutions',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Предложение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='popularsolutions',
            name='product',
            field=models.ManyToManyField(to='product.product', verbose_name='Популярный продукт'),
        ),
    ]
