# Generated by Django 5.0.1 on 2024-02-01 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourservice',
            old_name='descriptoin',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='ourworks',
            old_name='descriptoin',
            new_name='description',
        ),
    ]
