# Generated by Django 5.0.1 on 2024-01-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_application_options_alter_application_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='company',
        ),
        migrations.AddField(
            model_name='application',
            name='descriptoin',
            field=models.TextField(max_length=500, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Почта'),
        ),
    ]
