# Generated by Django 5.0.1 on 2024-01-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_application_company_application_descriptoin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='descriptoin',
            new_name='description',
        ),
    ]
