# Generated by Django 5.0.1 on 2024-01-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_rename_descriptoin_application_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=20, verbose_name='ФИО'),
        ),
    ]
