# Generated by Django 5.0.1 on 2024-02-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_occasion_application_occasion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='occasion',
        ),
        migrations.AddField(
            model_name='application',
            name='occasion',
            field=models.CharField(choices=[('ONE', 'Test')], default='', max_length=3),
            preserve_default=False,
        ),
    ]
