# Generated by Django 5.0.1 on 2024-02-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_application_occasion_application_occasion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Occasion',
        ),
        migrations.AlterField(
            model_name='application',
            name='occasion',
            field=models.CharField(choices=[('ONE', 'Просто заявка'), ('TWO', 'Калькулятор')], max_length=3, verbose_name='Повод заявки'),
        ),
    ]
