# Generated by Django 5.0.1 on 2024-02-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('one', '7'), ('two', '14'), ('three', '30')], max_length=5)),
                ('system_type', models.CharField(choices=[('AHD', 'AHD'), ('IP', 'IP')], max_length=4)),
                ('quality', models.CharField(choices=[('HD', 'HD'), ('FullHD', 'FullHD'), ('2K-4K', '2K-4K')], max_length=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
