# Generated by Django 5.0.1 on 2024-02-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Номер телефона'),
        ),
    ]
