# Generated by Django 5.0.1 on 2024-02-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_camera_domestic_camera_external_alter_camera_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='price',
            field=models.IntegerField(),
        ),
    ]
