# Generated by Django 5.0.1 on 2024-02-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_camera_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='price',
            new_name='total_price',
        ),
    ]
