# Generated by Django 5.0.1 on 2024-02-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_rename_price_camera_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='time',
            field=models.CharField(choices=[('7', '7'), ('14', '14'), ('30', '30')], max_length=5),
        ),
    ]
