# Generated by Django 5.0.1 on 2024-02-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_alter_camera_domestic_alter_camera_external_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'verbose_name': 'Конфигурации камер', 'verbose_name_plural': 'Конфигурации камер'},
        ),
    ]
