# Generated by Django 5.0.1 on 2024-03-10 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0009_alter_camera_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camera",
            name="description",
        ),
        migrations.RemoveField(
            model_name="camera",
            name="email",
        ),
        migrations.RemoveField(
            model_name="camera",
            name="name",
        ),
        migrations.RemoveField(
            model_name="camera",
            name="number",
        ),
    ]
