# Generated by Django 4.2.13 on 2024-08-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculatorblockcategoryproductsdata",
            name="name",
            field=models.CharField(default=111, verbose_name="Название категории"),
            preserve_default=False,
        ),
    ]
