# Generated by Django 4.2.13 on 2024-08-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_calculatorblockcategoryproductsdata_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationwithfile",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="media/application",
                verbose_name="Приложенный файл",
            ),
        ),
    ]
