# Generated by Django 4.2.13 on 2024-10-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0003_alter_applicationwithfile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationwithcalculator",
            name="calculator_data",
            field=models.JSONField(default={}, verbose_name="Данные из калькулятора"),
            preserve_default=False,
        ),
    ]
