# Generated by Django 4.2.13 on 2024-10-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0004_applicationwithcalculator_calculator_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calculatorblockdata",
            name="calculator_data",
        ),
        migrations.RemoveField(
            model_name="calculatordata",
            name="application",
        ),
        migrations.RemoveField(
            model_name="optiondata",
            name="block_data",
        ),
        migrations.DeleteModel(
            name="CalculatorBlockCategoryProductsData",
        ),
        migrations.DeleteModel(
            name="CalculatorBlockData",
        ),
        migrations.DeleteModel(
            name="CalculatorData",
        ),
        migrations.DeleteModel(
            name="OptionData",
        ),
    ]
