# Generated by Django 4.2.13 on 2024-10-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0006_application_created_at_application_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "chat_id",
                    models.IntegerField(
                        db_index=True, unique=True, verbose_name="ID чата пользователя"
                    ),
                ),
                (
                    "send_application",
                    models.BooleanField(
                        default=False, verbose_name="Уведомлять о заявках"
                    ),
                ),
            ],
            options={
                "verbose_name": "Телеграм чат",
                "verbose_name_plural": "Телеграм чаты",
            },
        ),
    ]
