# Generated by Django 4.2.11 on 2024-05-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_rename_quantity_сam_register_quantity_cam"),
    ]

    operations = [
        migrations.RenameField(
            model_name="register",
            old_name="max_quantity_hdd",
            new_name="max_size_hdd",
        ),
        migrations.RemoveField(
            model_name="product",
            name="nutrition",
        ),
        migrations.RemoveField(
            model_name="register",
            name="nutrition",
        ),
        migrations.AddField(
            model_name="product",
            name="power_supply",
            field=models.CharField(
                default=2, max_length=30, verbose_name="Электропитание"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="register",
            name="power_supply",
            field=models.CharField(
                default=2, max_length=50, verbose_name="Электропитание"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hdd",
            name="description",
            field=models.CharField(max_length=5000, verbose_name="Описание"),
        ),
    ]
