# Generated by Django 4.2.11 on 2024-05-17 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("product", "0009_rename_max_quantity_hdd_register_max_size_hdd_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=20, verbose_name="Тип")),
                (
                    "form_factor",
                    models.CharField(max_length=20, verbose_name="Форм Фактор"),
                ),
                (
                    "accommodation",
                    models.CharField(max_length=30, verbose_name="Размещение"),
                ),
                (
                    "resolution",
                    models.CharField(max_length=30, verbose_name="Разрешение"),
                ),
                (
                    "dark",
                    models.CharField(max_length=30, verbose_name="Съемка в темноте"),
                ),
                (
                    "temperature",
                    models.CharField(max_length=30, verbose_name="Температура"),
                ),
                (
                    "power_supply",
                    models.CharField(max_length=30, verbose_name="Электропитание"),
                ),
                (
                    "microphone",
                    models.CharField(max_length=30, verbose_name="Микрофон"),
                ),
                ("micro_sd", models.CharField(max_length=30, verbose_name="MicroSD")),
                (
                    "viewing_angle",
                    models.CharField(max_length=30, verbose_name="Угол Обзора"),
                ),
                ("focus", models.CharField(max_length=30, verbose_name="Фокус")),
                ("price", models.IntegerField(default=0, verbose_name="Цена")),
            ],
            options={
                "verbose_name": "Камера",
                "verbose_name_plural": "Камеры",
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="accommodation",
        ),
        migrations.RemoveField(
            model_name="product",
            name="dark",
        ),
        migrations.RemoveField(
            model_name="product",
            name="focus",
        ),
        migrations.RemoveField(
            model_name="product",
            name="form_factor",
        ),
        migrations.RemoveField(
            model_name="product",
            name="micro_sd",
        ),
        migrations.RemoveField(
            model_name="product",
            name="microphone",
        ),
        migrations.RemoveField(
            model_name="product",
            name="power_supply",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="resolution",
        ),
        migrations.RemoveField(
            model_name="product",
            name="temperature",
        ),
        migrations.RemoveField(
            model_name="product",
            name="type",
        ),
        migrations.RemoveField(
            model_name="product",
            name="viewing_angle",
        ),
        migrations.RemoveField(
            model_name="register",
            name="article",
        ),
        migrations.RemoveField(
            model_name="register",
            name="description",
        ),
        migrations.RemoveField(
            model_name="register",
            name="image",
        ),
        migrations.RemoveField(
            model_name="register",
            name="manufacturer",
        ),
        migrations.RemoveField(
            model_name="register",
            name="model",
        ),
        migrations.AddField(
            model_name="product",
            name="object_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                upload_to="media/product", verbose_name="Изображение"
            ),
        ),
        migrations.RemoveField(
            model_name="product",
            name="manufacturer",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=2,
                max_length=100,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="manufacturer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.manufacturer",
                verbose_name="Производитель",
            ),
            preserve_default=False,
        ),
    ]
