# Generated by Django 4.2.11 on 2024-05-17 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_camera_remove_product_accommodation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="category",
            new_name="content_type",
        ),
    ]
