# Generated by Django 4.2.11 on 2024-05-17 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("product", "0012_rename_content_type_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camera",
            name="id",
        ),
        migrations.RemoveField(
            model_name="camera",
            name="price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="register",
            name="id",
        ),
        migrations.RemoveField(
            model_name="register",
            name="price",
        ),
        migrations.AddField(
            model_name="camera",
            name="product_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="product.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=0, verbose_name="Цена"),
        ),
        migrations.AddField(
            model_name="register",
            name="product_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="product.product",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.category",
                verbose_name="Категория",
            ),
        ),
    ]
