# Generated by Django 4.2.11 on 2024-05-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0013_remove_camera_id_remove_camera_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="accommodation",
            field=models.CharField(
                help_text="Название поля: accommodation",
                max_length=30,
                verbose_name="Размещение",
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="dark",
            field=models.CharField(
                help_text="Название поля: dark",
                max_length=30,
                verbose_name="Съемка в темноте",
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="focus",
            field=models.CharField(
                help_text="Название поля: focus", max_length=30, verbose_name="Фокус"
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="form_factor",
            field=models.CharField(
                help_text="Название поля: form_factor",
                max_length=20,
                verbose_name="Форм Фактор",
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="micro_sd",
            field=models.CharField(
                help_text="Название поля: micro_sd",
                max_length=30,
                verbose_name="MicroSD",
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="microphone",
            field=models.CharField(
                help_text="Название поля: microphone",
                max_length=30,
                verbose_name="Микрофон",
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="power_supply",
            field=models.CharField(
                help_text="Название поля: power_supply",
                max_length=30,
                verbose_name="Электропитание",
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="resolution",
            field=models.CharField(
                help_text="Название поля: resolution",
                max_length=30,
                verbose_name="Разрешение",
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="temperature",
            field=models.CharField(
                help_text="Название поля: temperature",
                max_length=30,
                verbose_name="Температура",
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="type",
            field=models.CharField(
                help_text="Название поля: type", max_length=20, verbose_name="Тип"
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="viewing_angle",
            field=models.CharField(
                help_text="Название поля: viewing_angle",
                max_length=30,
                verbose_name="Угол Обзора",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(
                default=0, help_text="Название поля: price", verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="register",
            name="max_resolution",
            field=models.CharField(
                help_text="Название поля: max_resolution",
                max_length=50,
                verbose_name="Максимально разрешение",
            ),
        ),
        migrations.AlterField(
            model_name="register",
            name="max_size_hdd",
            field=models.IntegerField(
                help_text="Название поля: max_size_hdd",
                verbose_name="Макс объем HDD Тб",
            ),
        ),
        migrations.AlterField(
            model_name="register",
            name="power_supply",
            field=models.CharField(
                help_text="Название поля: power_supply",
                max_length=50,
                verbose_name="Электропитание",
            ),
        ),
        migrations.AlterField(
            model_name="register",
            name="quantity_cam",
            field=models.IntegerField(
                help_text="Название поля: quantity_cam", verbose_name="Количество камер"
            ),
        ),
        migrations.AlterField(
            model_name="register",
            name="quantity_hdd",
            field=models.IntegerField(
                help_text="Название поля: quantity_hdd", verbose_name="Количество hhd"
            ),
        ),
    ]
