# Generated by Django 4.2.13 on 2024-06-01 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0014_alter_camera_accommodation_alter_camera_dark_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadySolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Название")),
                (
                    "image",
                    models.ImageField(
                        upload_to="media/ready", verbose_name="Фотография"
                    ),
                ),
                (
                    "tooltip_text",
                    models.TextField(max_length=200, verbose_name="Подсказка"),
                ),
                (
                    "description",
                    models.TextField(max_length=5000, verbose_name="Описание"),
                ),
                (
                    "price",
                    models.IntegerField(blank=True, null=True, verbose_name="Цена"),
                ),
            ],
            options={
                "verbose_name": "Готовые решение",
                "verbose_name_plural": "Готовые решение",
            },
        ),
        migrations.CreateModel(
            name="SolutionToProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="Кол-во")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
                (
                    "solution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.readysolution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Тэг",
                "verbose_name_plural": "Тэги",
            },
        ),
        migrations.RenameModel(
            old_name="Image_Works",
            new_name="ImageWorks",
        ),
        migrations.RenameModel(
            old_name="Category",
            new_name="ProductCategory",
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={
                "verbose_name": "Производитель",
                "verbose_name_plural": "Производители",
            },
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Название"),
        ),
        migrations.DeleteModel(
            name="ReadySolutions",
        ),
        migrations.AddField(
            model_name="readysolution",
            name="tags",
            field=models.ManyToManyField(to="product.tag", verbose_name="Тэги"),
        ),
    ]
