# Generated by Django 4.2.13 on 2024-06-01 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0015_readysolution_solutiontoproduct_tag_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Категория вопросов",
                "verbose_name_plural": "Категории вопросов",
            },
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={
                "verbose_name": "Категория продукции",
                "verbose_name_plural": "Категории продукции",
            },
        ),
        migrations.RenameField(
            model_name="questions",
            old_name="questions",
            new_name="question",
        ),
        migrations.AlterField(
            model_name="solutiontoproduct",
            name="solution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment",
                to="product.readysolution",
            ),
        ),
        migrations.AlterField(
            model_name="questions",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="product.questionscategory",
                verbose_name="Категории",
            ),
        ),
    ]
