# Generated by Django 4.2.13 on 2024-06-01 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0016_questionscategory_alter_productcategory_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Questions",
        ),
        migrations.DeleteModel(
            name="QuestionsCategory",
        ),
    ]
