# Generated by Django 4.2.13 on 2024-06-01 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0017_delete_questions_delete_questionscategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ourworks",
            name="deadline",
        ),
        migrations.RemoveField(
            model_name="ourworks",
            name="equipped",
        ),
        migrations.RemoveField(
            model_name="ourworks",
            name="image",
        ),
        migrations.RemoveField(
            model_name="ourworks",
            name="main_image",
        ),
        migrations.AddField(
            model_name="imageworks",
            name="is_main",
            field=models.BooleanField(
                default=False, verbose_name="Картинка на главной"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="imageworks",
            name="work",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="product.ourworks",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ourworks",
            name="area",
            field=models.IntegerField(default=100, verbose_name="Площадь работ"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ourworks",
            name="time",
            field=models.IntegerField(default=1, verbose_name="Затраченное время"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ourservice",
            name="title",
            field=models.CharField(max_length=400, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="ourworks",
            name="add_date",
            field=models.DateTimeField(verbose_name="Дата добавления на сайт"),
        ),
        migrations.AlterField(
            model_name="ourworks",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ourworks",
            name="title",
            field=models.CharField(max_length=300, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="register",
            name="quantity_hdd",
            field=models.IntegerField(
                help_text="Название поля: quantity_hdd", verbose_name="Количество HDD"
            ),
        ),
    ]
