# Generated by Django 4.2.13 on 2024-06-01 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0018_remove_ourworks_deadline_remove_ourworks_equipped_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hdd",
            name="price",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена",
            ),
        ),
        migrations.AlterField(
            model_name="ourworks",
            name="area",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Площадь работ",
            ),
        ),
        migrations.AlterField(
            model_name="ourworks",
            name="budget",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Бюджет",
            ),
        ),
        migrations.AlterField(
            model_name="ourworks",
            name="time",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Затраченное время",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(
                default=0,
                help_text="Название поля: price",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена",
            ),
        ),
        migrations.AlterField(
            model_name="readysolution",
            name="price",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена",
            ),
        ),
        migrations.AlterField(
            model_name="register",
            name="max_size_hdd",
            field=models.IntegerField(
                help_text="Название поля: max_size_hdd",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Макс объем HDD Тб",
            ),
        ),
        migrations.AlterField(
            model_name="register",
            name="quantity_cam",
            field=models.IntegerField(
                help_text="Название поля: quantity_cam",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Количество камер",
            ),
        ),
        migrations.AlterField(
            model_name="register",
            name="quantity_hdd",
            field=models.IntegerField(
                help_text="Название поля: quantity_hdd",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Количество HDD",
            ),
        ),
        migrations.AlterField(
            model_name="solutiontoproduct",
            name="amount",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Кол-во",
            ),
        ),
    ]
