# Generated by Django 4.2.13 on 2024-06-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0019_alter_hdd_price_alter_ourworks_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ourservice",
            name="action",
            field=models.CharField(
                default="Подробнее", max_length=20, verbose_name="Текст кнопки"
            ),
        ),
    ]
