# Generated by Django 4.2.13 on 2024-07-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0020_ourservice_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="ourworks",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="На главной"),
        ),
    ]
