# Generated by Django 4.2.13 on 2024-07-09 14:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0021_ourworks_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="FACP",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="product.product",
                    ),
                ),
                (
                    "alarm_loops",
                    models.IntegerField(
                        help_text="Название поля: alarm_loops",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Кол-во шлейфов сигнализации",
                    ),
                ),
                (
                    "wireless_sensor_support",
                    models.BooleanField(
                        default=False,
                        help_text="Название поля: wireless_sensor_support",
                        verbose_name="Поддержка беспроводных извещателей",
                    ),
                ),
                (
                    "phone_control",
                    models.BooleanField(
                        default=False,
                        help_text="Название поля: phone_control",
                        verbose_name="Управление с телефона",
                    ),
                ),
                (
                    "temperature",
                    models.CharField(
                        help_text="Название поля: temperature",
                        max_length=30,
                        verbose_name="Рабочая температура",
                    ),
                ),
            ],
            options={
                "verbose_name": "ППКОП",
                "verbose_name_plural": "ППКОПы",
            },
            bases=("product.product",),
        ),
        migrations.CreateModel(
            name="PACSProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="product.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар СКУД",
                "verbose_name_plural": "Товары СКУД",
            },
            bases=("product.product",),
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="product.product",
                    ),
                ),
                (
                    "temperature",
                    models.CharField(
                        help_text="Название поля: temperature",
                        max_length=30,
                        verbose_name="Рабочая температура",
                    ),
                ),
            ],
            options={
                "verbose_name": "Извещатель",
                "verbose_name_plural": "Извещатели",
            },
            bases=("product.product",),
        ),
        migrations.AlterField(
            model_name="camera",
            name="temperature",
            field=models.CharField(
                help_text="Название поля: temperature",
                max_length=30,
                verbose_name="Рабочая температура",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="article",
            field=models.CharField(blank=True, max_length=100, verbose_name="Артикул"),
        ),
        migrations.AlterField(
            model_name="product",
            name="model",
            field=models.CharField(
                help_text="Название поля: model", max_length=300, verbose_name="Модель"
            ),
        ),
        migrations.DeleteModel(
            name="HDD",
        ),
    ]
