# Generated by Django 4.2.13 on 2024-07-09 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0022_facp_pacsproduct_sensor_alter_camera_temperature_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HDD",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="product.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "HDD",
                "verbose_name_plural": "HDD",
            },
            bases=("product.product",),
        ),
    ]
