# Generated by Django 4.2.13 on 2024-07-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0023_hdd"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camera",
            name="micro_sd",
        ),
        migrations.RemoveField(
            model_name="camera",
            name="microphone",
        ),
        migrations.AddField(
            model_name="camera",
            name="resolution_type",
            field=models.CharField(
                blank=True,
                help_text="Название поля: resolution_type",
                max_length=30,
                verbose_name="Тип разрешения",
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="resolution",
            field=models.CharField(
                help_text="Название поля: resolution",
                max_length=50,
                verbose_name="Разрешение",
            ),
        ),
    ]
