# Generated by Django 4.2.13 on 2024-07-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0024_remove_camera_micro_sd_remove_camera_microphone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="micro_sd",
            field=models.BooleanField(
                default=False,
                help_text="Название поля: micro_sd",
                max_length=30,
                verbose_name="Поддержка MicroSD",
            ),
        ),
        migrations.AddField(
            model_name="camera",
            name="micro_sd_details",
            field=models.TextField(
                blank=True,
                help_text="Название поля: micro_sd_details",
                verbose_name="Подробности для MicroSD",
            ),
        ),
        migrations.AddField(
            model_name="camera",
            name="microphone",
            field=models.BooleanField(
                default=False,
                help_text="Название поля: microphone",
                max_length=30,
                verbose_name="Наличичие микрофона",
            ),
        ),
        migrations.AddField(
            model_name="camera",
            name="microphone_details",
            field=models.TextField(
                blank=True,
                help_text="Название поля: microphone_details",
                verbose_name="Подробности для микрофона",
            ),
        ),
    ]
