# Generated by Django 4.2.13 on 2024-07-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0025_camera_micro_sd_camera_micro_sd_details_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="accommodation",
            field=models.CharField(
                help_text="Название поля: accommodation",
                max_length=50,
                verbose_name="Размещение",
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="focus",
            field=models.CharField(
                help_text="Название поля: focus", max_length=50, verbose_name="Фокус"
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="form_factor",
            field=models.CharField(
                help_text="Название поля: form_factor",
                max_length=50,
                verbose_name="Форм Фактор",
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="viewing_angle",
            field=models.CharField(
                help_text="Название поля: viewing_angle",
                max_length=50,
                verbose_name="Угол Обзора",
            ),
        ),
    ]
