# Generated by Django 4.2.13 on 2024-07-26 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0026_alter_camera_accommodation_alter_camera_focus_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="product.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Остальной товар",
                "verbose_name_plural": "Остальные товары",
            },
            bases=("product.product",),
        ),
        migrations.RemoveField(
            model_name="pacsproduct",
            name="product_ptr",
        ),
        migrations.DeleteModel(
            name="HDD",
        ),
        migrations.DeleteModel(
            name="PACSProduct",
        ),
    ]
