# Generated by Django 4.2.13 on 2024-07-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0027_otherproduct_remove_pacsproduct_product_ptr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(max_length=5000, verbose_name="Описание"),
        ),
    ]
