# Generated by Django 4.2.13 on 2024-07-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0028_alter_product_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="readysolution",
            options={
                "verbose_name": "Готовые решение",
                "verbose_name_plural": "Готовые решения",
            },
        ),
        migrations.AlterField(
            model_name="readysolution",
            name="tooltip_text",
            field=models.TextField(max_length=1000, verbose_name="Подсказка"),
        ),
    ]
