# Generated by Django 4.2.13 on 2024-07-29 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0030_hdd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hdd",
            name="capacity",
            field=models.IntegerField(
                help_text="Название поля: capacity",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Ёмкость, tb",
            ),
        ),
    ]
