# Generated by Django 4.2.13 on 2024-08-10 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0035_blockoption_initial_value_and_more"),
        ("product", "0032_solutiontoproduct_is_link_solutiontoproduct_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="solutiontoproduct",
            name="calculator_block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="calculator.calculatorblock",
            ),
        ),
        migrations.AlterField(
            model_name="solutiontoproduct",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.product",
            ),
        ),
    ]
