# Generated by Django 4.2.13 on 2024-08-10 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0033_solutiontoproduct_calculator_block_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solutiontoproduct",
            name="amount",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Кол-во",
            ),
        ),
    ]
