# Generated by Django 4.2.13 on 2024-09-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0035_imageworks_created_at_imageworks_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tooltip",
            field=models.TextField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Информация в тултипе",
            ),
        ),
    ]
