# Generated by Django 4.2.13 on 2024-10-12 03:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0036_product_tooltip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ourworks",
            name="product",
        ),
        migrations.AddField(
            model_name="productcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="product.productcategory",
            ),
        ),
        migrations.CreateModel(
            name="OurWorksProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Краткое описание",
                        max_length=200,
                        verbose_name="Текст",
                    ),
                ),
                (
                    "is_link",
                    models.BooleanField(
                        default=False,
                        help_text="Отобразить как ссылку на товар",
                        verbose_name="Ссылка",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Кол-во",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "our_work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.ourworks",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
