# Generated by Django 4.2.13 on 2024-10-12 04:15

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0037_remove_ourworks_product_productcategory_parent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="level",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productcategory",
            name="lft",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productcategory",
            name="rght",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productcategory",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="product.productcategory",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="title",
            field=models.CharField(max_length=50, unique=True, verbose_name="Название"),
        ),
    ]
