# Generated by Django 4.2.13 on 2024-10-12 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0039_alter_ourworksproduct_our_work"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ourworksproduct",
            name="our_work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="product.ourworks",
            ),
        ),
    ]
