# Generated by Django 4.2.13 on 2024-11-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0040_alter_ourworksproduct_our_work"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="type",
            field=models.CharField(
                default="AHD",
                help_text="Название поля: type",
                max_length=50,
                verbose_name="Тип",
            ),
            preserve_default=False,
        ),
    ]
