# Generated by Django 4.2.13 on 2024-11-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0042_newproduct_producttype_typeproperty_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producttypetypeproperty",
            options={
                "verbose_name": "Хар-ка вида товара",
                "verbose_name_plural": "Хар-ки видов товаров",
            },
        ),
        migrations.AlterModelOptions(
            name="typeproperty",
            options={"verbose_name": "Хар-ка", "verbose_name_plural": "Хар-ки"},
        ),
    ]
