# Generated by Django 4.2.13 on 2024-11-11 19:28

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0043_alter_producttypetypeproperty_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productproperty",
            options={
                "ordering": ("property",),
                "verbose_name": "Хар-ка товара",
                "verbose_name_plural": "Хар-ки товаров",
            },
        ),
        migrations.AlterField(
            model_name="newproduct",
            name="model",
            field=models.CharField(max_length=300, verbose_name="Модель"),
        ),
        migrations.AlterField(
            model_name="newproduct",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Цена",
            ),
        ),
        migrations.AlterField(
            model_name="newproduct",
            name="product_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="product.producttype",
                verbose_name="Вид товара",
            ),
        ),
    ]
