# Generated by Django 4.2.13 on 2024-11-11 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0045_alter_typeproperty_property_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newproduct",
            options={
                "verbose_name": "Новый товар",
                "verbose_name_plural": "Новые товары",
            },
        ),
    ]
