# Generated by Django 4.2.13 on 2025-02-14 15:07

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0047_alter_ourworksproduct_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readysolution",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=12,
                verbose_name="Корректировка цены",
            ),
        ),
    ]
