# Generated by Django 4.2.13 on 2025-02-14 16:06

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0048_alter_readysolution_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readysolution",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                help_text="Дополнительная сумма к цене оборудования. Может быть отрицательной для скидки.",
                max_digits=12,
                verbose_name="Корректировка цены",
            ),
        ),
    ]
