# Generated by Django 4.2.13 on 2025-02-14 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0049_alter_readysolution_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="solutiontoproduct",
            options={
                "ordering": ("position", "pk"),
                "verbose_name": "Товар к готовому решению",
                "verbose_name_plural": "Товары к готовым решениям",
            },
        ),
        migrations.AddField(
            model_name="solutiontoproduct",
            name="position",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Позиция в списке",
            ),
        ),
    ]
