# Generated by Django 4.2.13 on 2025-04-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0052_alter_newproduct_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facp",
            name="product_ptr",
        ),
        migrations.RemoveField(
            model_name="hdd",
            name="product_ptr",
        ),
        migrations.RemoveField(
            model_name="otherproduct",
            name="product_ptr",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="manufacturer",
        ),
        migrations.RemoveField(
            model_name="product",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="register",
            name="product_ptr",
        ),
        migrations.RemoveField(
            model_name="sensor",
            name="product_ptr",
        ),
        migrations.DeleteModel(
            name="Camera",
        ),
        migrations.DeleteModel(
            name="FACP",
        ),
        migrations.DeleteModel(
            name="HDD",
        ),
        migrations.DeleteModel(
            name="OtherProduct",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="Register",
        ),
        migrations.DeleteModel(
            name="Sensor",
        ),
    ]
