# Generated by Django 4.2.13 on 2024-06-01 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuestionsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Категория вопросов",
                "verbose_name_plural": "Категории вопросов",
            },
        ),
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200, verbose_name="Вопрос")),
                ("answer", models.TextField(max_length=500, verbose_name="Ответ")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social.questionscategory",
                        verbose_name="Категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос/Ответ",
                "verbose_name_plural": "Вопрос/Ответ",
            },
        ),
    ]
