# Generated by Django 4.2.13 on 2024-06-02 21:36

import phonenumber_field.modelfields
from django.db import migrations, models

import social.validators


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_team_alter_questions_category_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=20, region=None, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Почта для связи"),
                ),
                (
                    "telegram",
                    models.URLField(
                        validators=[social.validators.validate_telegram_url],
                        verbose_name="Ссылка на телеграм для связи",
                    ),
                ),
                (
                    "whatsapp",
                    models.URLField(
                        validators=[social.validators.validate_whatsapp_url],
                        verbose_name="Ссылка на whatsapp для связи",
                    ),
                ),
                ("address", models.CharField(max_length=500, verbose_name="Адресс")),
            ],
        ),
    ]
