# Generated by Django 4.2.13 on 2024-06-02 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0003_socialinfo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "Работник", "verbose_name_plural": "Работники"},
        ),
        migrations.AlterModelOptions(
            name="socialinfo",
            options={"verbose_name": "Информация", "verbose_name_plural": "Информация"},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"verbose_name": "Команда", "verbose_name_plural": "Команды"},
        ),
        migrations.AddField(
            model_name="socialinfo",
            name="is_active",
            field=models.BooleanField(
                default=False, verbose_name="Актуальная информация"
            ),
        ),
        migrations.AddField(
            model_name="socialinfo",
            name="projects_done",
            field=models.IntegerField(
                default=1000,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Кол-во завершенных проектов",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="socialinfo",
            name="years",
            field=models.IntegerField(
                default=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Возраст компании",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Актуальная команда"),
        ),
    ]
