# Generated by Django 4.2.13 on 2024-06-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0004_alter_employee_options_alter_socialinfo_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionscategory",
            name="icon",
            field=models.ImageField(
                default=1,
                upload_to="media/questions/icons",
                verbose_name="Иконка категории",
            ),
            preserve_default=False,
        ),
    ]
