# Generated by Django 4.2.13 on 2024-06-03 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0005_questionscategory_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="OurGuarantees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.ImageField(upload_to="", verbose_name="Иконка")),
                ("title", models.CharField(max_length=30, verbose_name="Название")),
                ("is_big", models.BooleanField(verbose_name="Большая карточка")),
                ("is_active", models.BooleanField(verbose_name="На главной")),
            ],
            options={
                "verbose_name": "Подкатегория гарантии",
                "verbose_name_plural": "Подкатегории гарантий",
            },
        ),
        migrations.CreateModel(
            name="Subguarantees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(verbose_name="Текст")),
                (
                    "guarantee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subguarantees",
                        to="social.ourguarantees",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подкатегория гарантии",
                "verbose_name_plural": "Подкатегории гарантий",
            },
        ),
    ]
