# Generated by Django 4.2.13 on 2024-07-02 14:07

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0006_ourguarantees_subguarantees"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ourguarantees",
            options={
                "verbose_name": "Категория гарантий",
                "verbose_name_plural": "Категории гарантий",
            },
        ),
        migrations.RemoveField(
            model_name="socialinfo",
            name="years",
        ),
        migrations.AddField(
            model_name="socialinfo",
            name="founded",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Возраст компании"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=20,
                region=None,
                unique=True,
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="questions",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="social.questionscategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="socialinfo",
            name="address",
            field=models.CharField(max_length=500, verbose_name="Адрес"),
        ),
    ]
