# Generated by Django 4.2.13 on 2024-07-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0007_alter_ourguarantees_options_remove_socialinfo_years_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialinfo",
            name="founded",
            field=models.DateField(verbose_name="Компания основана"),
        ),
    ]
