# Generated by Django 4.2.13 on 2024-07-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0008_alter_socialinfo_founded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="answer",
            field=models.TextField(max_length=1000, verbose_name="Ответ"),
        ),
    ]
