# Generated by Django 4.2.13 on 2024-07-26 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0009_alter_questions_answer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ourguarantees",
            old_name="is_active",
            new_name="active",
        ),
        migrations.RenameField(
            model_name="socialinfo",
            old_name="is_active",
            new_name="active",
        ),
        migrations.RenameField(
            model_name="team",
            old_name="is_active",
            new_name="active",
        ),
    ]
